name: Provision SQS Queue

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment name (dev, staging, prod)"
        required: true
        default: "dev"
      queue_base_name:
        description: "Base name for the SQS queue"
        required: true
        default: "video-processing"

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Create SQS Queue
      id: create_queue
      run: |+
        ENV="${{ github.event.inputs.environment }}"
        BASE="${{ github.event.inputs.queue_base_name }}"
        QUEUE_NAME="${BASE}-${ENV}"

        echo "Checking if SQS queue exists: $QUEUE_NAME"

        # Try to get the queue URL (if exists)
        QUEUE_URL=$(aws sqs get-queue-url --queue-name "$QUEUE_NAME" --query 'QueueUrl' --output text 2>/dev/null || true)

        if [ -z "$QUEUE_URL" ] || [[ "$QUEUE_URL" == "None" ]]; then
          echo "Queue does not exist. Creating SQS queue: $QUEUE_NAME"
          QUEUE_URL=$(aws sqs create-queue \
            --queue-name "$QUEUE_NAME" \
            --attributes VisibilityTimeout=630 \
            --query 'QueueUrl' \
            --output text)
        else
          echo "Queue exists. Updating SQS queue: $QUEUE_NAME"
          aws sqs set-queue-attributes \
            --queue-url "$QUEUE_URL" \
            --attributes VisibilityTimeout=630
        fi

        echo "Queue URL: $QUEUE_URL"

        # Save to GITHUB_ENV for later steps
        echo "QUEUE_URL=$QUEUE_URL" >> $GITHUB_ENV

    - name: Attach SQS Queue Policy for All S3 and All Lambda
      run: |+
        QUEUE_URL="$QUEUE_URL"
        QUEUE_ARN=$(aws sqs get-queue-attributes \
          --queue-url "$QUEUE_URL" \
          --attribute-names QueueArn \
          --query 'Attributes.QueueArn' \
          --output text)

        POLICY=$(jq -c --arg QUEUE_ARN "$QUEUE_ARN" '
        {
          Version: "2012-10-17",
          Statement: [
            {
              Sid: "Statement1",
              Effect: "Allow",
              Principal: "*",
              Action: "sqs:*",
              Resource: "*"
            }
          ]
        }')

        aws sqs set-queue-attributes \
          --queue-url "$QUEUE_URL" \
          --attributes "Policy=$POLICY"
                
    - name: Verify Queue
      run: |
        aws sqs get-queue-attributes \
          --queue-url "$QUEUE_URL" \
          --attribute-names All
